version: "3.9"

services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${evara_password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
volumes:
  postgres-data: