# Generated by Django 3.2.23 on 2023-12-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_token', models.CharField(help_text='For Found Password In System', max_length=100, verbose_name='Token')),
                ('password', models.CharField(help_text='Generated Password From Server', max_length=5, verbose_name='Password')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('isd', models.CharField(blank=True, help_text='International Subscriber Dialing For Iran: +98', max_length=10, null=True, verbose_name='ISD')),
            ],
        ),
    ]
