# Generated by Django 3.2.23 on 2023-12-25 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP DATA', 'verbose_name_plural': 'OTP DATA'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': "User's"},
        ),
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When Object Is Created', verbose_name='Create Time'),
            preserve_default=False,
        ),
    ]
